### ISSUE TITLE
June 20th Project Progress Scrum Report

### ISSUE THREAD

**Issue by ansel-rangers11** [anneguo3/budget-buddy#19]

**Comment by ansel-rangers11** [comment]
Ansel Hartanto o8c1b

I have worked on the basic Redux structure further as well as the skeleton for the summary page. I supported my group members in helping debug a bug. I also have set up the appropriate mongoDB and a mongo script (stubbed) that will be expanded on as we progressively get closer to hooking up the app to the DB.

I will be working on the filtering of transactions on the main page, database hooking up and the required code infrastructure for it using Express. I have not used Express so I will be exploring it further during my assignment so I can best apply it to our current project. 

I got stuck in determining how to best use MaterialUI but with the help of my group members I was able to overcome some design obstacles so that it fits into the page well.

**Comment by anneguo3** [comment]
Anne Guo l4j1b

I worked on setting up the reducer for our entry list and the add and delete actions to operate on the list, upon building off the stubs created by team-mates in the previous sprint, along with just cleaning up the overall file structure for the data page where this component lives.

  In the coming weeks, I will be adding the ability to categorize entries by adding an additional property and abstracting this out such that a user can actually determine the categories they would like to exist. I will also be supporting my teammate in setting up express and working on creating all the relevant routes for the entries page.

  I had gone through a learning hurdle in understanding how to use functional React components as that was the structure that was set-up by a team-mate, and gaining a solid basis of understanding for the nuances of hooks and how to leverage them throughout our project.

**Comment by elaineay** [comment]
Elaine Au-Yang c6f1b

I created the reducer for aggregating entries of income and expenses. I then took the aggregate information and connected it with the Recharts libraries for data visualization.

For the next sprint I will continue to add functionality (ie. reducers) for different ways to filter and view the data. This will include allowing users to customize spending limits or saving goals, and creating visuals for the respective filters.

The biggest obstacle in this sprint was learning how to use functional components versus the React classes we were introduced to during the workshop. It was confusing as to how the actions and store were all in one file, but once I understood it seemed that functional classes were a lot more streamlined than the class method we learned.

**Comment by BKsylvester** [comment]
h2i1b:

1. I worked on the routing for the overall app, the dynamic nav bar component which changes based on whether a user is logged in, as well as the account creation and sign in page.
2. In the next sprint I will be working on the authentication for user log in, POST for account creation, adding redux for the current user state, and the GET request to retrieve all user data upon login.
3. The biggest obstacle was learning how to use the react router as well as dealing with merge conflicts after reorganizing the structure of the app.
