### ISSUE TITLE
June 6th Project Progress Scrum Report 

### ISSUE THREAD

**Issue by ansel-rangers11** [anneguo3/budget-buddy#7]
Describe (for the project): (1) what you’ve worked on in the previous two weeks, (2) what you’ll be working on in the next two weeks, and (3) where you might have gotten stuck during the last two weeks.

**Comment by ansel-rangers11** [comment]
1) I have worked on the basic Redux structure for our app in abstracting components for scalability and allow basic functions such as delete and add to be viable for future iterations. Our app now shows a certain color for incoming money and another color for outgoing. The store and reducer is mostly constructed for further iterations. 
2) I will be working on the first iteration of the Summary page for our app as well as the ability fo filter transactions by certain dates (like data slicers). As I know Redux fairly well I will be assisting my team members with their progresses as well if need be. 
3) I got stuck for a while in imagining how our components abstract and interact with one another but after sketching it out on paper I was able to get a better grasp in our holistic overall design.

**Comment by anneguo3** [comment]
1) Over the last two weeks, I worked on creating the add entry component to our webpage, allowing the user to add all the information regarding an entry, through using MaterialUI and set-up the groundwork for the app,
2) Over the next two weeks, I'll be working on adding the functionality of making added method appear in the list and add functionality to delete any entries, along with adding the ability of categorizing any expense items or income items through categories (in a drop down)
3) I struggled with the Calendar component from MaterialUI in propagating the local user's current date, and tried numerous different "hard-coding" ways of solving it, but after scouring the web, I turned to using another external library that does the job more efficiently and effectively.

**Comment by sylvstrc** [comment]
H2i1b:
1. Over the last two weeks I worked on the Nav Bar, and Error Message components.
2. Over the next two weeks I will be working on the log in page, the account creation page, as well as routing for the different pages of the program.
3. For our project we used Material UI. As it was my first time using Material UI I struggled with customizing their components to fit them to our projects needs. It took a lot of googling, and reading through a lot of documentation to figure out how to use it properly.

**Comment by elaineay** [comment]
c6f1b:
1. Created components for the Data Overview text box as well as the components displaying individiaul data entries.
2. I will be creating the aggregation of data accumulated across all data entries as well as the visualization of this aggregate data.
3. Understanding how Material UI abstracted out react components had a learning curve to it, and I had to learn and unlearn some things I knew about react.

**Comment by dustxd** [comment]
@anneguo3 Not sure what you ended up using to handle localization but moment.js is a good library that offers a lot of flexibility :)
